title: Dita Julaika Putri # your name (or website title) here
logo: "/images/foto.jpeg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  An Informatic student at Telkom University. An ENFP who have high curiousity, have initiative, self motivated, concern to detail, fast learner, good in team work, willing to adapt with high changing and an enthusiastic person.
  <br><br>
  <a href="https://www.linkedin.com/in/dita-j/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
